[alias]
dev = ["watch", "-c", "-w", "src", "-x", "run -- --config config.yaml"]
# dev = ["watch", "--poll", "-c", "-w", "src", "-x", "run -- --config config.yaml"] # use this if on WSL and reload doesn't trigger